### ISSUE TITLE
Fails to Build

### ISSUE THREAD

**Issue by stef204** [HalosGhost/enlighten#23]
Fails to build  in a clean chroot on up-to-date system:

```
==> Extracting sources...
  -> Creating working copy of enlighten git repo...
Cloning into 'enlighten'...
done.
==> Starting prepare()...
DEVICE = "acpi_video0" ("intel_backlight")
SEARCH_PATH = "/sys/class/backlight:/sys/class/leds"
THRESHOLD_MAX = "100%"
THRESHOLD_MIN = "0"
TRANSITION_STEPS = "1"
TRANSITION_PAUSE = "0"
==> Starting pkgver()...
==> Starting build()...
overrides.mk:4: warning: overriding recipe for target 'install'
mke/rules:64: warning: ignoring old recipe for target 'install'
overrides.mk:12: warning: overriding recipe for target 'uninstall'
mke/rules:71: warning: ignoring old recipe for target 'uninstall'
make: *** No rule to make target 'dist/debug/enlighten', needed by 'check'.  Stop.
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```

Building using `makepkg` locally (not on clean chroot) results in: [this](https://paste.xinu.at/GE0B/).

And building from source _without_ using `PKGBUILD`: results in [this](https://paste.xinu.at/rKx/).

**Comment by HalosGhost** [comment]
Thank you for taking the time to open an issue! I've been slowly working on dramatically improving the developer experience for enlighten (as well as making it easier to contribute in case anyone would ever like to). Unsurprisingly, this has resulted in some changes that need new build procedures. I am sorry this caused you any headaches!

I just pushed a new version of the `PKGBUILD` to the AUR and it should hopefully build just fine for you now (note that the makedepends have changed). I will leave this issue open for a few days to give you a chance to try building it again and either letting me know if you run into any more issues (or, if I don't hear back from you, I will likely assume all is well).

Thank you again!

**Comment by stef204** [comment]
It builds and runs as expected now.  Thank you!

**Comment by HalosGhost** [comment]
I am very glad to hear that it all went well! I hope enlighten is working well for you. Thank you again for contributing!
