### ISSUE TITLE
list backlight devices

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/enlighten#3]
Do we want this? It'd be a crappy reimplementation of ``ls /sys/class/backlight``..

**Comment by meskarune** [comment]
It might be useful for people who don't want to have look up what dirs to check just for a device name. I know I have to look it up every time >.>

**Comment by HalosGhost** [comment]
that's a fair point, I suppose. And I suppose we could allow that directory to be configured at compile-time/run-time so that if you're on a weird OS (that still somehow provides the files we expect), then you can specify everything you need.

Heck, I guess we could have the specific properties be specifiable, but that seems like it might be going too far. For now, I suppose I'll aim at listing the current devices.

**Comment by meskarune** [comment]
alternatively you could just set the brightness for all devices inside that directory, but idk if that could possibly break things.

**Comment by HalosGhost** [comment]
No, I want it to be limited to one device at a time. Doing multiple devices could reasonably be handled with a shell script:

```bash
for i in intel_backlight lcd0 whatevs; do
    BACKLIGHT_DEVICE="$i" enlighten +9001
done
```

**Comment by HalosGhost** [comment]
hypothetically, via https://github.com/HalosGhost/enlighten/commit/4558eac949ce30ae0d23fd7c5322b08f9b81f746
